/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/desk.glb --types 
Author: Jinhong Jeong (https://sketchfab.com/JinhongJeong)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/office-desk-f63cfecaf29244a286a39c7180aa1329
Title: Office desk
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Object_2: THREE.Mesh;
    };
    materials: {
        material_0: THREE.MeshStandardMaterial;
    };
};

export function Desk(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/desk.glb') as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh
                position={[0, -4.7, 2]}
                geometry={nodes.Object_2.geometry}
                material={materials.material_0}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.05}
                receiveShadow
            />
        </group>
    );
}

useGLTF.preload('/desk.glb');
