/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/monitor.glb --types 
Author: Pricey1600 (https://sketchfab.com/Pricey1600)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/near-future-computer-monitor-87efc29297c944c6b2dac7b30b4e2084
Title: Near Future Computer Monitor
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Monitor_LP_lambert1_0: THREE.Mesh;
    };
    materials: {
        lambert1: THREE.MeshStandardMaterial;
    };
};

export function Monitor(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/monitor.glb') as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Monitor_LP_lambert1_0.geometry}
                material={materials.lambert1}
                rotation={[0, -Math.PI / 2, 0]}
                scale={0.11}
                castShadow
            />
        </group>
    );
}

useGLTF.preload('/monitor.glb');
