/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/ping_pong_table.glb --types 
Author: Digitalis Reality (https://sketchfab.com/digitalisreality)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-ping-pong-table-541b94352ae443be8e2bfb9de0e80865
Title: Low Poly Ping Pong Table
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        PingPongTable_metal_0: THREE.Mesh;
        PingPongTable_br_0: THREE.Mesh;
        PingPongTable_b001_0: THREE.Mesh;
        PingPongTable_w_0: THREE.Mesh;
        paddle_orange_accent_0: THREE.Mesh;
        paddle_orange_o_rubber_0: THREE.Mesh;
        paddle_orange_wood_0: THREE.Mesh;
        paddle_orange_darkwood_0: THREE.Mesh;
        paddle_red_accent_0: THREE.Mesh;
        paddle_red_r_rubber_0: THREE.Mesh;
        paddle_red_wood_0: THREE.Mesh;
        paddle_red_darkwood_0: THREE.Mesh;
        ball_ball_0: THREE.Mesh;
    };
    materials: {
        metal: THREE.MeshStandardMaterial;
        material: THREE.MeshStandardMaterial;
        ['b.001']: THREE.MeshStandardMaterial;
        material_3: THREE.MeshStandardMaterial;
        accent: THREE.MeshStandardMaterial;
        o_rubber: THREE.MeshStandardMaterial;
        wood: THREE.MeshStandardMaterial;
        darkwood: THREE.MeshStandardMaterial;
        r_rubber: THREE.MeshStandardMaterial;
        ball: THREE.MeshStandardMaterial;
    };
};

export function PingPongTable(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/ping_pong_table.glb') as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                    geometry={nodes.PingPongTable_metal_0.geometry}
                    material={materials.metal}
                />
                <mesh
                    geometry={nodes.PingPongTable_br_0.geometry}
                    material={materials.material}
                />
                <mesh
                    geometry={nodes.PingPongTable_b001_0.geometry}
                    material={materials['b.001']}
                />
                <mesh
                    geometry={nodes.PingPongTable_w_0.geometry}
                    material={materials.material_3}
                />
            </group>
            <group
                position={[-460.066, 254.741, 75.91]}
                rotation={[-Math.PI / 2, 0, -2.569]}
                scale={[41.913, 48.198, 48.198]}
            >
                <mesh
                    geometry={nodes.paddle_orange_accent_0.geometry}
                    material={materials.accent}
                />
                <mesh
                    geometry={nodes.paddle_orange_o_rubber_0.geometry}
                    material={materials.o_rubber}
                />
                <mesh
                    geometry={nodes.paddle_orange_wood_0.geometry}
                    material={materials.wood}
                />
                <mesh
                    geometry={nodes.paddle_orange_darkwood_0.geometry}
                    material={materials.darkwood}
                />
            </group>
            <group
                position={[458.891, 255.786, -81.663]}
                rotation={[-Math.PI / 2, 0, -0.421]}
                scale={[41.913, 48.198, 48.198]}
            >
                <mesh
                    geometry={nodes.paddle_red_accent_0.geometry}
                    material={materials.accent}
                />
                <mesh
                    geometry={nodes.paddle_red_r_rubber_0.geometry}
                    material={materials.r_rubber}
                />
                <mesh
                    geometry={nodes.paddle_red_wood_0.geometry}
                    material={materials.wood}
                />
                <mesh
                    geometry={nodes.paddle_red_darkwood_0.geometry}
                    material={materials.darkwood}
                />
            </group>
            <mesh
                geometry={nodes.ball_ball_0.geometry}
                material={materials.ball}
                position={[359.293, 266.441, -98.951]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={9.816}
            />
        </group>
    );
}

useGLTF.preload('/ping_pong_table.glb');
