/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/wooden_door.glb --types 
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-wooden-door-0b1053411bdb4af1b5a78a28887217aa
Title: Old wooden door
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Object_6: THREE.Mesh;
        Object_4: THREE.Mesh;
    };
    materials: {
        T_door_1: THREE.MeshStandardMaterial;
    };
};

export function WoodenDoor(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/wooden_door.glb') as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <group position={[-4.23, 0, 25.414]} scale={[5, 5, 5]}>
                <mesh
                    geometry={nodes.Object_4.geometry}
                    material={materials.T_door_1}
                />
                <mesh
                    geometry={nodes.Object_6.geometry}
                    material={materials.T_door_1}
                    position={[0.334, 1.236, -1.246]}
                />
                <pointLight
                    distance={20}
                    intensity={100}
                    position={[1.5, 2, 0]}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/wooden_door.glb');
